<?php
defined('PREVENT_DIRECT_ACCESS') OR exit('No direct script access allowed');

class PdfController extends Controller
{
    public function test()
    {
        require_once APP_DIR . 'libraries/PdfGenerator.php';
        $pdf = new PdfGenerator();

        $html = '
        <h2 style="text-align:center;color:#0ea5e9;">PDF Test Page</h2>
        <p>This is a test PDF generated by Dompdf using Composer autoload.</p>
        <table border="1" cellpadding="5" cellspacing="0" width="100%">
            <tr><th>ID</th><th>Name</th><th>Status</th></tr>
            <tr><td>1</td><td>John Doe</td><td>Active</td></tr>
        </table>';

        $pdf->generate($html, 'test.pdf', false);
    }
}
